name: dotnet-demo-api CI

on:
  pull_request:
  push:

jobs:
  test:
    uses: vojtechmares/dotnet-demo-api/.github/workflows/reusable-test.yml@main

  docker-build:
    needs: [test]
    uses: vojtechmares/dotnet-demo-api/.github/workflows/reusable-docker-build.yml@main

  deploy:
    needs: [docker-build]
    if: ${{ contains(github.ref, 'release') }}
    uses: vojtechmares/dotnet-demo-api/.github/workflows/reusable-deploy.yml@main
