name: dotnet-demo-api CI

on:
  pull_request:
  push:

jobs:
  test:
    uses: vojtechmares-examples/training-2025-03-13-ssd-github-actions-demo-dotnet-api/.github/workflows/reusable-test.yml@main
    with:
      dotnet-version: '9.0.x'

  docker-build:
    needs: [test]
    permissions:
      contents: read
      packages: write
    uses: vojtechmares-examples/training-2025-03-13-ssd-github-actions-demo-dotnet-api/.github/workflows/reusable-docker-build.yml@main
    secrets: inherit

  deploy:
    needs: [docker-build]
    if: ${{ contains(github.ref, 'release') }}
    uses: vojtechmares-examples/training-2025-03-13-ssd-github-actions-demo-dotnet-api/.github/workflows/reusable-deploy.yml@main
    with:
      environment: fake
