name: Tag on commits

on:
  push:
    branches:
      - release

jobs:
    tag:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}

        - name: Install svu
          run: |
            wget https://github.com/caarlos0/svu/releases/download/v3.2.2/svu_3.2.2_linux_amd64.tar.gz
            tar -xzf svu_3.2.2_linux_amd64.tar.gz
            sudo mv svu /usr/local/bin/
            sudo chmod +x /usr/local/bin/svu

        - name: Get tag
          run: |
            TAG=$(svu next)
            echo "TAG=${TAG}" >> $GITHUB_ENV

        - name: Create tag
          run: |
            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag ${TAG}
            git push origin ${TAG}
