name: Demo workflow

on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash

jobs:
  demo:
    runs-on: ubuntu-latest # self-hosted

    defaults:
      run:
        shell: pwsh

    steps:
      - name: pwsh hello world
        run: Write-Output "Hello world"
