name: Deploy

on:
  workflow_run:
    workflows: [".NET Test", "Docker build"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: fake

    concurrency:
      group: deploy-prod
      cancel-in-progress: true

    steps:
    - name: Fake deploy
      run: |
        sleep 330
        echo "Fake deploy"
