name: Integration testing demo

on: [push]

jobs:
  integration-testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        # credentials:
        #   username: ${{ secrets.dockerhub_username }}
        #   password: ${{ secrets.dockerhub_password }}
        ports:
          - 5432/tcp

    steps:
      - name: Wait for Postgres database to be ready
        env:
          RETRIES: 5
        run: |
          # real retry/wait command
          # until psql -h $PG_HOST -U $PG_USER -d $PG_DATABASE -c "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
          # dummy wait
          until [ $RETRIES -eq 0 ]; do
            echo "Waiting for PostgreSQL to become ready, $((RETRIES--)) attempts remaining..."
            sleep 5
          done

      - name: Run integration tests
        run: echo "Running integration tests..."
