name: Strategy matrix demo

on: [push]

jobs:
  nodejs-compatibility-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [18, 20, 22, 23] # last 3 LTS releases and latest stable

    steps:
      - name: Set up Node.js version ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Test
        continue-on-error: ${{ matrix.version == 23 }}
        run: |
          echo "Running tests..."
