name: Test all (on all branches)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet restore
        run: dotnet restore 

      - name: dotnet build
        run: dotnet build --no-restore

      - name: dotnet test
        run: dotnet test --no-build --verbosity normal
