name: Workflow with needs on jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fake build
        run: echo "Build"

  publish-artifact:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Upload build artifact
        run: echo "Fake upload"

