name: Workflow with needs on jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fake build
        run: echo "Build"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          sleep 30
          echo "Running tests..." && false

  publish-artifact:
    runs-on: ubuntu-latest
    needs: [ build, test ]

    steps:
      - name: Upload build artifact
        run: echo "Fake upload"

  create-release:
    runs-on: ubuntu-latest

    needs: [publish-artifact]

    steps:
      - name: Create release
        run: echo "Creating release..."
